### PR TITLE
Generated layout for the ultra-low-power comparator

### PR DESCRIPTION
**Pull request by RTimothyEdwards**
Generated layout for the ultra-low-power comparator and resolved a few issues in the schematic.

### CODE REVIEW

**Comment by RTimothyEdwards** [comment]
I needed layout for this block so I created the layout myself.  In the process I discovered one issue with the schematic, which is that the level shifters in Stage1 are connected to dvdd/dvss, but dvdd and dvss are not declared pins on the schematic and symbol.  So I corrected this.  I have not checked if you were declaring these to be globals in the testbench, because otherwise I cannot see how the netlist would be able to simulate.

**Comment by JYSquare2** [comment]
Thank you for checking out the schematic. I believe that's the major part I was missed out causing the whole circuit cannot function and stuck on it unable continue for layout generation. Thanks again.

**Comment by RTimothyEdwards** [comment]
If you can continue with simulation validation, it would be very helpful to me.  While the shuttle run deadline is in two days, I expect to have a few additional days to finish the test chip before data goes to SkyWater.

**Comment by JYSquare2** [comment]
I will recheck the simulations based on the updated design.

**Pull request merged**
